TARGET_COMPANIES = [
    {
        "name": "Elm",
        "sector": "Digital government and technology",
        "priority": "high",
        "why": "Strong data, analytics, and digital government work.",
    },
    {
        "name": "SDAIA",
        "sector": "Data and AI government authority",
        "priority": "high",
        "why": "Core Saudi data and AI ecosystem.",
    },
    {
        "name": "Digital Government Authority",
        "sector": "Digital government",
        "priority": "high",
        "why": "Digital transformation initiatives and government data needs.",
    },
    {
        "name": "MCIT",
        "sector": "Technology government ministry",
        "priority": "medium",
        "why": "Technology programs, initiatives, and possible early hiring signals.",
    },
    {
        "name": "CST",
        "sector": "Communications, space, and technology regulator",
        "priority": "medium",
        "why": "Technology-sector signals and possible analytics opportunities.",
    },
    {
        "name": "HRDF",
        "sector": "Employment support",
        "priority": "high",
        "why": "Tamheer, training, and employment pathways.",
    },
    {
        "name": "Monsha'at",
        "sector": "SME and entrepreneurship",
        "priority": "medium",
        "why": "Startup and SME initiatives that may create analytics opportunities.",
    },
    {
        "name": "Saudi Post SPL",
        "sector": "Logistics and government services",
        "priority": "medium",
        "why": "Logistics and operations analytics potential.",
    },
    {
        "name": "Etimad",
        "sector": "Government procurement platform",
        "priority": "medium",
        "why": "Digital platform with reporting and analytics needs.",
    },
    {
        "name": "NHC",
        "sector": "Housing and real estate",
        "priority": "medium",
        "why": "Large national housing data and reporting needs.",
    },
    {
        "name": "stc",
        "sector": "Telecom and digital services",
        "priority": "high",
        "why": "Large data teams, dashboards, customer analytics, and BI needs.",
    },
    {
        "name": "Mobily",
        "sector": "Telecom",
        "priority": "medium",
        "why": "Telecom companies have continuous reporting and analytics needs.",
    },
    {
        "name": "Zain KSA",
        "sector": "Telecom",
        "priority": "medium",
        "why": "Potential BI, customer analytics, and operations analytics roles.",
    },
    {
        "name": "Tahakom",
        "sector": "Smart mobility and public safety technology",
        "priority": "high",
        "why": "Data-heavy operations with analytics and reporting potential.",
    },
    {
        "name": "Mozn",
        "sector": "AI, data, and fintech risk",
        "priority": "high",
        "why": "Strong data culture and potential analytics-adjacent roles.",
    },
    {
        "name": "Lean Technologies",
        "sector": "Fintech",
        "priority": "high",
        "why": "Fintech data use cases and growth analytics opportunities.",
    },
    {
        "name": "Tamara",
        "sector": "Fintech",
        "priority": "high",
        "why": "Fast-growing fintech with BI, risk, product, and growth analytics needs.",
    },
    {
        "name": "Tabby",
        "sector": "Fintech",
        "priority": "high",
        "why": "Regional fintech with analytics, reporting, and data roles.",
    },
    {
        "name": "Foodics",
        "sector": "SaaS and restaurant technology",
        "priority": "high",
        "why": "SaaS business with product, customer, and sales analytics needs.",
    },
    {
        "name": "Lucidya",
        "sector": "Customer experience and social analytics",
        "priority": "medium",
        "why": "Analytics-focused product and potential data roles.",
    },
    {
        "name": "HungerStation",
        "sector": "Delivery and marketplace",
        "priority": "high",
        "why": "Operations, growth, and marketplace analytics use cases.",
    },
    {
        "name": "Jahez",
        "sector": "Delivery and marketplace",
        "priority": "high",
        "why": "Public Saudi company with strong operations analytics potential.",
    },
    {
        "name": "Noon",
        "sector": "E-commerce",
        "priority": "medium",
        "why": "Retail, operations, and marketplace analytics opportunities.",
    },
    {
        "name": "Careem",
        "sector": "Mobility and delivery",
        "priority": "medium",
        "why": "Regional platform with operations and growth analytics needs.",
    },
    {
        "name": "Mrsool",
        "sector": "Delivery and logistics",
        "priority": "medium",
        "why": "Potential operations reporting and marketplace analytics.",
    },
    {
        "name": "Nana",
        "sector": "Grocery delivery",
        "priority": "medium",
        "why": "Retail and delivery analytics opportunities.",
    },
    {
        "name": "Al Rajhi Bank",
        "sector": "Banking",
        "priority": "high",
        "why": "Large analytics, reporting, risk, finance, and customer data needs.",
    },
    {
        "name": "SNB",
        "sector": "Banking",
        "priority": "high",
        "why": "Large bank with BI, risk, finance, and customer analytics opportunities.",
    },
    {
        "name": "Riyad Bank",
        "sector": "Banking",
        "priority": "high",
        "why": "Banking analytics and reporting roles are common and valuable.",
    },
    {
        "name": "SAB",
        "sector": "Banking",
        "priority": "medium",
        "why": "Potential finance, risk, and reporting analytics opportunities.",
    },
    {
        "name": "Alinma Bank",
        "sector": "Banking",
        "priority": "medium",
        "why": "Banking and digital transformation analytics potential.",
    },
    {
        "name": "Bank Albilad",
        "sector": "Banking",
        "priority": "medium",
        "why": "Potential reporting, finance, and customer analytics roles.",
    },
    {
        "name": "PwC Middle East",
        "sector": "Consulting",
        "priority": "high",
        "why": "Consulting projects often need analysts, dashboards, and reporting.",
    },
    {
        "name": "Deloitte",
        "sector": "Consulting",
        "priority": "high",
        "why": "Analytics, transformation, and reporting projects.",
    },
    {
        "name": "EY",
        "sector": "Consulting",
        "priority": "high",
        "why": "Data, assurance, finance, and transformation analytics work.",
    },
    {
        "name": "KPMG",
        "sector": "Consulting",
        "priority": "high",
        "why": "Consulting, audit, and transformation analytics opportunities.",
    },
    {
        "name": "Accenture",
        "sector": "Consulting and technology",
        "priority": "high",
        "why": "Technology and analytics projects with enterprise clients.",
    },
    {
        "name": "Devoteam",
        "sector": "Digital consulting",
        "priority": "medium",
        "why": "Digital transformation and analytics-related projects.",
    },
    {
        "name": "SAMA",
        "sector": "Financial regulator",
        "priority": "high",
        "why": "Strong match with Abdullah's SAMA POS portfolio project.",
    },
    {
        "name": "Tadawul Group",
        "sector": "Capital markets",
        "priority": "high",
        "why": "Financial market data and reporting opportunities.",
    },
    {
        "name": "Saudi Tourism Authority",
        "sector": "Tourism",
        "priority": "medium",
        "why": "Tourism data and public-data project opportunities.",
    },
    {
        "name": "Saudia",
        "sector": "Airline",
        "priority": "medium",
        "why": "Operations, customer, revenue, and punctuality analytics potential.",
    },
    {
        "name": "Riyadh Air",
        "sector": "Airline",
        "priority": "medium",
        "why": "Growing airline with early data and reporting team signals.",
    },
    {
        "name": "flynas",
        "sector": "Airline",
        "priority": "medium",
        "why": "Operations and customer analytics potential.",
    },
    {
        "name": "Tawuniya",
        "sector": "Insurance",
        "priority": "medium",
        "why": "Insurance analytics, reporting, and customer data needs.",
    },
    {
        "name": "Bupa Arabia",
        "sector": "Insurance and healthcare",
        "priority": "medium",
        "why": "Healthcare insurance data and reporting opportunities.",
    },
    {
        "name": "Nahdi",
        "sector": "Retail pharmacy",
        "priority": "medium",
        "why": "Retail, inventory, sales, and customer analytics potential.",
    },
    {
        "name": "Jarir",
        "sector": "Retail",
        "priority": "medium",
        "why": "Retail sales and inventory analytics opportunities.",
    },
    {
        "name": "Panda Retail",
        "sector": "Retail",
        "priority": "medium",
        "why": "Large retail operations with reporting and analytics needs.",
    },
    {
        "name": "Extra",
        "sector": "Retail",
        "priority": "medium",
        "why": "Retail and sales analytics potential.",
    },
    {
        "name": "SAL",
        "sector": "Logistics",
        "priority": "medium",
        "why": "Logistics and operations analytics opportunities.",
    },
    {
        "name": "ROSHN",
        "sector": "Real estate and PIF company",
        "priority": "medium",
        "why": "PIF company with reporting, operations, and market analytics needs.",
    },
    {
        "name": "Diriyah Company",
        "sector": "Giga project and PIF company",
        "priority": "medium",
        "why": "Large project environment with analytics and reporting needs.",
    },
    {
        "name": "NEOM",
        "sector": "Giga project",
        "priority": "medium",
        "why": "Large digital and operations environment with potential analytics roles.",
    },
    {
        "name": "Red Sea Global",
        "sector": "Tourism and giga project",
        "priority": "medium",
        "why": "Tourism and operations analytics potential.",
    },
]
